sudo: false

branches:
    only:
        - master

services:
    - docker

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build . -t $DOCKER_USERNAME/junos-ex-telegraf
    - docker push $DOCKER_USERNAME/junos-ex-telegraf